const sources = [
  {
    "id": "ID01",
    "title": "BBC Archive",
    "url": "https://www.bbc.com/topics/c01yxyz46myt",
    "provider": "BBC",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Friedensschlüsse und Ordnung des Friedens in der Moderne",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Europäische Integration, Kalter Krieg",
    "sourceType": "Video; Text; Bild",
    "language": "",
    "description": "",
    "notes": ""
  },
  {
    "id": "ID02",
    "title": "EU Screen",
    "url": "http://www.euscreen.eu/",
    "provider": "EU Screen",
    "subject": "",
    "contentField": "Friedensschlüsse und Ordnung des Friedens in der Moderne , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Menschenrechte in historischer Perspektive, Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive",
    "timeCategory": "20. Jahrhundert, 19. Jahrhundert",
    "eventCategory": "Europäischer Imperialismus, Erster Weltkrieg, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Europäische Integration",
    "sourceType": "Video, Bildquellen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Digitale Quellen",
    "language": "Deutsch; Englisch",
    "description": "Euscreen offers free access to thousands of archival audiovisual items. Our collection provides insight into the social, cultural, political, and economic events that have shaped the 20th and 21st centuries.",
    "notes": ""
  },
  {
    "id": "ID03",
    "title": "ARD History Channel",
    "url": "https://www.ardmediathek.de/panorama",
    "provider": "ARD",
    "subject": "",
    "contentField": "Friedensschlüsse und Ordnung des Friedens in der Moderne , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Audiovisuelle Quellen",
    "language": "Deutsch; Englisch",
    "description": "",
    "notes": ""
  },
  {
    "id": "ID04",
    "title": "United States Holocaust Memorial Museum",
    "url": "https://www.ushmm.org/de",
    "provider": "",
    "subject": "",
    "contentField": "Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "",
    "sourceType": "Bildquellen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Statistiken und/oder Diagramme, Digitale Quellen",
    "language": "Englisch; Deutsch",
    "description": "A living memorial to the Holocaust, the United States Holocaust Memorial Museum inspires citizens and leaders worldwide to confront antisemitism and hatred, prevent genocide, and promote human dignity. A nonpartisan, federal educational institution chartered by a unanimous Act of Congress in 1980, the Museum’s permanent place on the National Mall is guaranteed by federal support, and its far-reaching educational programs and global impact are made possible by generous donors.",
    "notes": ""
  },
  {
    "id": "ID05",
    "title": "BBC Archive",
    "url": "https://www.bbc.com/topics/c01yxyz46myt",
    "provider": "",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Audiovisuelle Quellen , Bildquellen , Digitale Quellen",
    "language": "Englisch",
    "description": "",
    "notes": ""
  },
  {
    "id": "ID06",
    "title": "SWR Archivradio",
    "url": "https://www.swr.de/swrkultur/wissen/archivradio/",
    "provider": "",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Audiovisuelle Quellen",
    "language": "Deutsch",
    "description": "",
    "notes": ""
  },
  {
    "id": "ID07",
    "title": "Österreichische Nationbibliothek",
    "url": "https://anno.onb.ac.at/",
    "provider": "",
    "subject": "",
    "contentField": "Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Nationalismus",
    "sourceType": "Textquellen , Bildquellen , Karikaturen",
    "language": "Deutsch",
    "description": "ANNO (AustriaN Newspaper Online) ist der virtuelle Zeitungslesesaal der Österreichischen Nationalbibliothek. In ANNO kann in historischen österreichischen Zeitungen und Zeitschriften online geblättert, gelesen und gesucht werden.",
    "notes": ""
  },
  {
    "id": "ID08",
    "title": "The British Newspaper Archive",
    "url": "https://www.britishnewspaperarchive.co.uk/",
    "provider": "British Library",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Nationalismus , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg",
    "sourceType": "Textquellen , Bildquellen",
    "language": "Englisch",
    "description": "The British Newspaper Archive is a partnership between the British Library and Findmypast to digitise the British Library's vast collection of newspapers.",
    "notes": ""
  },
  {
    "id": "ID09",
    "title": "Universität Heidelberg - Zeitungsarchiv",
    "url": "https://www.ub.uni-heidelberg.de/helios/digi/zeitungen_titel.html",
    "provider": "Universität Heidelberg",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Industrialisierung, Nationalismus , Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS",
    "sourceType": "Bildquellen , Karikaturen , Textquellen",
    "language": "Deutsch",
    "description": "Digitalsat von Zeitungen",
    "notes": ""
  },
  {
    "id": "ID10",
    "title": "Hessische Regionalzeitungen aus der Zeit des Ersten Weltkrieges",
    "url": "https://hwk1.hebis.de/1914/",
    "provider": "",
    "subject": "",
    "contentField": "Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Erster Weltkrieg",
    "sourceType": "Bildquellen , Textquellen , Karten",
    "language": "Deutsch",
    "description": "",
    "notes": ""
  },
  {
    "id": "ID11",
    "title": "OutHistory",
    "url": "https://outhistory.org",
    "provider": "OutHistory",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Weimarer Republik, Deutschland im NS",
    "sourceType": "Bildquellen , Textquellen , Digitale Quellen",
    "language": "Englisch",
    "description": "OutHistory is a public history website that aims to generate, present, and promote high-quality evidence-based LGBTQ historical research for LGBTQ and general audiences. We also work to foster the development and growth of broad and diverse communities of people interested in learning about and producing LGBTQ histories. We are especially interested in under-represented histories and historical research that contributes to positive social change. Most but not all of the current content focuses on the United States and Canada, sometimes in larger transnational contexts.",
    "notes": ""
  },
  {
    "id": "ID12",
    "title": "Digitale Bibliothek München",
    "url": "https://www.digitale-sammlungen.de/",
    "provider": "Münchener Digitale Bibliothek",
    "subject": "",
    "contentField": "Islamische Welt - christliche Welt: Begegnung zweier Kulturen in Mittelalter und früher Neuzeit , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert",
    "timeCategory": "18. Jahrhundert",
    "eventCategory": "",
    "sourceType": "Bildquellen , Karikaturen , Karten , Textquellen",
    "language": "Deutsch",
    "description": "Das Münchener DigitalisierungsZentrum bringt seit 1997 die reichhaltigen Bestände der Bayerischen Staatsbibliothek (BSB) ins Internet.",
    "notes": ""
  },
  {
    "id": "ID13",
    "title": "Der Spiegel",
    "url": "https://www.spiegel.de/spiegel/print/index-2024.html",
    "provider": "",
    "subject": "",
    "contentField": "Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne , Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Europäische Integration, Kalter Krieg  , Zweiter Weltkrieg , Holocaust und Erinnerungskultur , Deutschland im NS",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen",
    "language": "Deutsch",
    "description": "Das Digitalarchiv des Spiegel Magazins.",
    "notes": ""
  },
  {
    "id": "ID14",
    "title": "British Cartoon Archive",
    "url": "https://www.cartoons.ac.uk/",
    "provider": "University of Kent",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Nationalismus , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Karikaturen , Bildquellen",
    "language": "Englisch",
    "description": "The British Cartoon Archive (BCA) is dedicated to the history of British cartooning over the last two hundred years.",
    "notes": ""
  },
  {
    "id": "ID15",
    "title": "Bildpostkartenarchiv der Universität Osnabrück",
    "url": "https://bildpostkarten.uni-osnabrueck.de/",
    "provider": "",
    "subject": "",
    "contentField": "Die moderne Industriegesellschaft zwischen Fortschritt und Krise",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Erster Weltkrieg, Europäischer Imperialismus, Industrialisierung",
    "sourceType": "Bildquellen",
    "language": "Deutsch",
    "description": "",
    "notes": ""
  },
  {
    "id": "ID16",
    "title": "Frauen in Bewegung 1848-1938",
    "url": "https://fraueninbewegung.onb.ac.at/",
    "provider": "Österreichische Nationalbibliothek",
    "subject": "",
    "contentField": "Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Menschenrechte in historischer Perspektive, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Industrialisierung, Deutschland im NS, Erster Weltkrieg, Europäischer Imperialismus",
    "sourceType": "Textquellen , Karikaturen , Bildquellen , Zeitgenössische Bilder",
    "language": "Deutsch",
    "description": "Biografien, Vereinsprofile, Dokumente der Frauenbewegung Österreichs im 20. Jahrhundert.",
    "notes": ""
  },
  {
    "id": "ID17",
    "title": "Sammlung Judaica der Goethe-Universität Frankfurt",
    "url": "https://sammlungen.ub.uni-frankfurt.de/judaica",
    "provider": "Goethe Universität Frankfurt am Main",
    "subject": "",
    "contentField": "Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Nationalismus , Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg",
    "sourceType": "Textquellen , Bildquellen",
    "language": "Deutsch",
    "description": "Die Judaica Sammlung in der Frankfurter Universitätsbibliothek stellt die größte Judaica- und Hebraica Sammlung in Deutschland dar und zählt weltweit zu den bedeutendsten Sammlungen ihrer Art.",
    "notes": ""
  },
  {
    "id": "ID18",
    "title": "German History in Documents and Images",
    "url": "https://ghdi.ghi-dc.org/",
    "provider": "German Historical Institute, Washington, DC.",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert, 18. Jahrhundert",
    "eventCategory": "Nationalismus , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Textquellen",
    "language": "Englisch; Deutsch",
    "description": "",
    "notes": ""
  },
  {
    "id": "ID19",
    "title": "Europäische Geschichte Online",
    "url": "https://ieg-ego.eu/",
    "provider": "Verschiedene",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Kalter Krieg  , Nationalismus",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Statistiken und/oder Diagramme, Karten",
    "language": "Englisch; Deutsch",
    "description": "",
    "notes": ""
  },
  {
    "id": "ID20",
    "title": "Mémorial de la Shoah",
    "url": "https://www.memorialdelashoah.org/",
    "provider": "Mémorial de la Shoah - Gedenkstätten der Shoah in Frankreich",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Holocaust und Erinnerungskultur",
    "sourceType": "Bildquellen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Karten",
    "language": "Englisch; Deutsch",
    "description": "Die Gedenkstätte der Shoah hat Ressourcen verschiedener Art für Lehrer und Erzieher zusammengestellt und ausgewählt, die das junge Publikum mit der Geschichte der Shoah vertraut machen oder mit ihren Schülern einen bestimmten Aspekt der Zeit des Zweiten Weltkriegs vertiefen möchten. global und das Unterfangen der Verfolgung und Vernichtung der europäischen Juden.",
    "notes": ""
  },
  {
    "id": "ID21",
    "title": "Interview-Archiv Zwangsarbeit",
    "url": "https://www.zwangsarbeit-archiv.de/",
    "provider": "Freie Universität Berlin",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg",
    "sourceType": "Audiovisuelle Quellen , Bildquellen , Textquellen , Digitale Quellen",
    "language": "Englisch; Deutsch",
    "description": "Das Interview-Archiv \"Zwangsarbeit 1939-1945\" erinnert an über zwanzig Millionen Menschen, die für das nationalsozialistische Deutschland arbeiten mussten. Es enthält knapp 600 Audio und Video-Interviews mit ehemaligen Zwangsarbeiterinnen und Zwangsarbeitern aus 26 Ländern. Dazu gibt es Transkripte, Übersetzungen, Fotos und Kurzbiografien.",
    "notes": ""
  }
];
    
