const sources = [
  {
    "id": "ID01",
    "title": "17-Jun-53",
    "url": "https://www.17juni53.de/home/index.html",
    "provider": "Bundeszentrale für politische Bildung",
    "subject": "",
    "contentField": "Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Kalter Krieg  ",
    "sourceType": "Karten , Bildquellen , Zeitgenössische Bilder, Textquellen ",
    "language": "Deutsch",
    "description": "Der Aufstand vom 17. Juni jährt sich 2013 zum sechzigsten Mal. Er war die erste Massenerhebung im Machtbereich der Sowjetunion überhaupt und eines der Schlüsselereignisse, die den Gang der deutsch-deutschen Geschichte bis zur Einheit im Jahr 1990 maßgeblich mitbestimmt haben.\nUnsere Website ist vor zehn Jahren erarbeitet und recherchiert worden und ging zum fünfzigsten Jahrestag online. Die Erkenntnisse und Deutungsmuster über den Volksaufstand haben sich seither gefestigt und sind in der öffentlichen Wahrnehmung verankert.\nZum sechzigsten Jahrestag haben wir unsere Website einem kritischen Blick unterzogen: Die zahleichen O-Töne, Fotos, Karten, Dokumente und Grafiken vermitteln nach wie vor ein dem aktuellen Forschungsstand adäquates Bild vom 17. Juni 1953. Wir bieten deshalb die gesamte Breite unserer Recherche weiterhin in dieser Online-Chronik an, ohne eine Aktualisierung vorzunehmen. Allein die Bibliographie aus dem Jahr 2002 haben wir aktualisiert und um eine neue Publikationsliste ergänzt.\nDie materialreiche Website steht zeitgeschichtlich interessierten Nutzerinnen und Nutzern als thematisches Archiv auch in Zukunft offen.\n"
  },
  {
    "id": "ID02",
    "title": "100(0) Schlüsseldokumente zur russischen und sowjetischen Geschichte",
    "url": "https://www.1000dokumente.de/",
    "provider": "Bayrische Staatspolitik",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Deutschland im NS, Nationalismus , Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Holocaust und Erinnerungskultur , Zweiter Weltkrieg ",
    "sourceType": "Bildquellen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen ",
    "language": "Deutsch",
    "description": "Sammlung von 137 Schlüsseldokumenten zur deutschen Geschichte im 20. Jahrhundert (von 1903 bis 1998)"
  },
  {
    "id": "ID03",
    "title": "Anno: Historische österreichische Zeitungen und Zeitschriften",
    "url": "https://anno.onb.ac.at/alph_list.htm",
    "provider": "Österreichische Nationalbibliothek",
    "subject": "",
    "contentField": "Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert ",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Industrialisierung, Nationalismus , Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS",
    "sourceType": "Textquellen , Bildquellen ",
    "language": "Deutsch",
    "description": "Liste aller elektronisch verfügbaren Zeitungen und Zeitschriften."
  },
  {
    "id": "ID04",
    "title": "ARD History Channel",
    "url": "https://www.ardmediathek.de/panorama",
    "provider": "ARD",
    "subject": "",
    "contentField": "Friedensschlüsse und Ordnung des Friedens in der Moderne , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive ",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Audiovisuelle Quellen ",
    "language": "Deutsch; Englisch",
    "description": "Das Panorama-Archiv: Eine Zeitreise durch 60 Jahre politische Geschichte."
  },
  {
    "id": "ID05",
    "title": "Arolsen Archive",
    "url": "https://collections.arolsen-archives.org/de/search",
    "provider": "Arolsen Archives",
    "subject": "",
    "contentField": "Die Menschenrechte in historischer Perspektive, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Deutschland im NS, Holocaust und Erinnerungskultur ",
    "sourceType": "Bildquellen , Zeitgenössische Bilder, Textquellen ",
    "language": "",
    "description": "Die Arolsen Archives geben Auskünfte über NS-Verfolgte, sichern den Erhalt des Archivs für die nächsten Generationen und nehmen viele weitere wichtige Aufgaben wahr. Unsere Arbeit ist facettenreich und unsere Geschichte bewegt: Schon länger, als es die Bundesrepublik gibt, sind wir fester Bestandteil der Aufarbeitung der nationalsozialistischen Geschichte und ihrer Auswirkungen im internationalen Kontext."
  },
  {
    "id": "ID06",
    "title": "Augspurgische Ordinari Postzeitung von Staats-, gelehrten, historisch- u. ökonomischen Neuigkeiten — Augsburger Postzeitung: 1768 bis 1848\nDigitalisierte Jahrgänge: 1768 - 1848.",
    "url": "http://digital.bib-bvb.de/collections/UBA/#/collection/DTL-2677",
    "provider": "Universitätsbibliothek Augsburg",
    "subject": "",
    "contentField": "Die moderne Industriegesellschaft zwischen Fortschritt und Krise",
    "timeCategory": "",
    "eventCategory": "Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS",
    "sourceType": "Textquellen , Bildquellen ",
    "language": "Deutsch",
    "description": " Enthält u.a. Hand- und Druckschriften, aber auch Ausgaben der \"\"Augspurgischen Ordinari Postzeitung aus dem 18. und 19. Jhd."
  },
  {
    "id": "ID07",
    "title": "BBC Archive",
    "url": "https://www.bbc.com/topics/c01yxyz46myt",
    "provider": "BBC",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Europäische Integration, Kalter Krieg  ",
    "sourceType": "Bildquellen , Zeitgenössische Bilder, Audiovisuelle Quellen ",
    "language": "Englisch",
    "description": "Curated extracts from the BBC's huge content archive."
  },
  {
    "id": "ID08",
    "title": "BBC Archive",
    "url": "https://www.bbc.com/topics/c01yxyz46myt",
    "provider": "BBC",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Audiovisuelle Quellen , Bildquellen , Digitale Quellen",
    "language": "Englisch",
    "description": "Curated extracts from the BBC's huge content archive."
  },
  {
    "id": "ID09",
    "title": "Bildpostkartenarchiv der Universität Osnabrück",
    "url": "https://bildpostkarten.uni-osnabrueck.de/",
    "provider": "Universität Osnabrück",
    "subject": "",
    "contentField": "Die moderne Industriegesellschaft zwischen Fortschritt und Krise",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Erster Weltkrieg, Europäischer Imperialismus, Industrialisierung",
    "sourceType": "Bildquellen ",
    "language": "Deutsch",
    "description": "Sammlung von Postkarten des 19. und 20. Jahrhunderts."
  },
  {
    "id": "ID10",
    "title": "British Cartoon Archive",
    "url": "https://www.cartoons.ac.uk/",
    "provider": "University of Kent",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert ",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Nationalismus , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Karikaturen , Bildquellen ",
    "language": "Englisch",
    "description": "The British Cartoon Archive (BCA) is dedicated to the history of British cartooning over the last two hundred years."
  },
  {
    "id": "ID11",
    "title": "Bundeszentrale für politische Bildung",
    "url": "https://www.bpb.de/",
    "provider": "BPD",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Nationalismus , Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Statistiken und/oder Diagramme, Karten , Digitale Quellen",
    "language": "Deutsch",
    "description": "Die Bundeszentrale für politische Bildung (bpb) bietet als staatliche Fachinstitution ein breites Spektrum an verlässlichen Quellen zu Politik, Zeitgeschichte und Gesellschaft."
  },
  {
    "id": "ID12",
    "title": "Compact Memory - Jüdische Geschichte im deutschsprachigen Raum",
    "url": "https://sammlungen.ub.uni-frankfurt.de/cm",
    "provider": "Goethe Universität Frankfurt am Main",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen ",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Holocaust und Erinnerungskultur , Deutschland im NS, Weimarer Republik, Erster Weltkrieg, Nationalismus ",
    "sourceType": "Textquellen , Bildquellen , Zeitgenössische Bilder",
    "language": "Deutsch",
    "description": "\"\"Das Portal Compact Memory umfasst 500 jüdische Zeitungen und Zeitschriften des vorwiegend deutschsprachigen Raumes aus den Jahren 1768-1938. Die Periodika repräsentieren die gesamte religiöse, politische, soziale, literarische und wissenschaftliche Bandbreite der jüdischen Gemeinschaft und der \"\"Wissenschaft des Judentums\"\"."
  },
  {
    "id": "ID13",
    "title": "Der Spiegel",
    "url": "https://www.spiegel.de/spiegel/print/index-2024.html",
    "provider": "Der Spiegel",
    "subject": "",
    "contentField": "Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne , Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Europäische Integration, Kalter Krieg  , Zweiter Weltkrieg , Holocaust und Erinnerungskultur , Deutschland im NS",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen ",
    "language": "Deutsch",
    "description": "Das Digitalarchiv des Spiegel Magazins."
  },
  {
    "id": "ID14",
    "title": "Die Quellen sprechen",
    "url": "Die-Quellen-sprechen.de",
    "provider": "Bayerischer Rundfunk",
    "subject": "",
    "contentField": "Die Menschenrechte in historischer Perspektive, Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Holocaust und Erinnerungskultur , Weimarer Republik, Zweiter Weltkrieg ",
    "sourceType": "Audiovisuelle Quellen , Textquellen ",
    "language": "Deutsch",
    "description": "Die Verfolgung und Ermordung der europäischen Juden\ndurch das nationalsozialistische Deutschland 1933—1945"
  },
  {
    "id": "ID15",
    "title": "Die Stasi-Mediathek",
    "url": "https://www.stasi-mediathek.de/",
    "provider": "Bundesarchiv",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Kalter Krieg  ",
    "sourceType": "Bildquellen , Textquellen , Karten , Audiovisuelle Quellen , Zeitgenössische Bilder",
    "language": "Englisch",
    "description": "Die Stasi-Mediathek bietet einen einfachen, multimedialen Zugang zu ausgewählten Inhalten des Stasi-Unterlagen-Archivs. Die online gestellten Dokumente veranschaulichen die Wirkungsweise der DDR-Geheimpolizei. Neben Aktenmaterial beinhaltet dieses Onlineangebot Videos, Tonbandaufnahmen und Fotos der Stasi."
  },
  {
    "id": "ID16",
    "title": "Dokumentationszentrum und Museum über die Migration in Deutschland",
    "url": "https://domid.org",
    "provider": "Domid (eigener Verein)",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Europäische Integration",
    "sourceType": "Bildquellen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Statistiken und/oder Diagramme, Karten ",
    "language": "Englisch; Deutsch",
    "description": "Das Museum von DOMiD erzählt die Geschichte der Migrationsgesellschaft."
  },
  {
    "id": "ID17",
    "title": "EU Screen",
    "url": "http://www.euscreen.eu/",
    "provider": "EU Screen",
    "subject": "",
    "contentField": "Friedensschlüsse und Ordnung des Friedens in der Moderne , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Menschenrechte in historischer Perspektive, Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive ",
    "timeCategory": "20. Jahrhundert, 19. Jahrhundert",
    "eventCategory": "Europäischer Imperialismus, Erster Weltkrieg, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Europäische Integration",
    "sourceType": "Video, Bildquellen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Digitale Quellen",
    "language": "Deutsch; Englisch",
    "description": "Euscreen offers free access to thousands of archival audiovisual items. Our collection provides insight into the social, cultural, political, and economic events that have shaped the 20th and 21st centuries."
  },
  {
    "id": "ID18",
    "title": "Europäische Geschichte Online",
    "url": "https://ieg-ego.eu/",
    "provider": "Leibniz Institute of European History (IEG)",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert ",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Kalter Krieg  , Nationalismus ",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Statistiken und/oder Diagramme, Karten ",
    "language": "Englisch; Deutsch",
    "description": "EGO examines 500 years of modern European history by transcending national, disciplinary and methodological boundaries."
  },
  {
    "id": "ID19",
    "title": "Europeana",
    "url": "https://www.europeana.eu/de",
    "provider": "Europeana Foundation",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Nationalismus , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg ",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Karten ",
    "language": "Englisch; Deutsch",
    "description": "Metadatenbank: Digitale Sammlung kulturelles Erbe Europas"
  },
  {
    "id": "ID20",
    "title": "Flugschriften 1848 Universitätsbibliothek UB",
    "url": "https://sammlungen.ub.uni-frankfurt.de/1848",
    "provider": "Goethe Universität Frankfurt am Main",
    "subject": "",
    "contentField": "Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert ",
    "timeCategory": "19. Jahrhundert",
    "eventCategory": "Nationalismus ",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Textquellen ",
    "language": "Deutsch",
    "description": "Kleinschrifttum der Revolution 1848"
  },
  {
    "id": "ID21",
    "title": "Frauen in Bewegung 1848-1938",
    "url": "https://fraueninbewegung.onb.ac.at/",
    "provider": "Österreichische Nationalbibliothek",
    "subject": "",
    "contentField": "Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Menschenrechte in historischer Perspektive, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert ",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Industrialisierung, Deutschland im NS, Erster Weltkrieg, Europäischer Imperialismus",
    "sourceType": "Textquellen , Karikaturen , Bildquellen , Zeitgenössische Bilder",
    "language": "Deutsch",
    "description": "Biografien, Vereinsprofile, Dokumente der Frauenbewegung Österreichs im 20. Jahrhundert."
  },
  {
    "id": "ID22",
    "title": "German History in Documents and Images",
    "url": "https://ghdi.ghi-dc.org/",
    "provider": "German Historical Institute, Washington, DC.",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert, 18. Jahrhundert",
    "eventCategory": "Nationalismus , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Textquellen ",
    "language": "Englisch; Deutsch",
    "description": "German History in Documents and Images (GHDI) is a comprehensive collection of primary source materials documenting Germany's political, social, and cultural history from 1500 to the present."
  },
  {
    "id": "ID23",
    "title": "Geschichte (wirlernenonline.de)",
    "url": "https://wirlernenonline.de/geschichte",
    "provider": "Wir lernen Online",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Islamische Welt - christliche Welt: Begegnung zweier Kulturen in Mittelalter und früher Neuzeit , Die Menschenrechte in historischer Perspektive, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Nationalismus , 1789 Französische Revolution , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg ",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen ",
    "language": "Deutsch",
    "description": "Onlinelernplattform"
  },
  {
    "id": "ID24",
    "title": "Hessische Regionalzeitungen aus der Zeit des Ersten Weltkrieges",
    "url": "https://hwk1.hebis.de/1914/",
    "provider": "hebis-Verbundzentrale",
    "subject": "",
    "contentField": "Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Erster Weltkrieg, 1789 Französische Revolution , Nationalismus , Industrialisierung, Europäischer Imperialismus, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Europäische Integration, Kalter Krieg  ",
    "sourceType": "Bildquellen , Textquellen , Karten ",
    "language": "Deutsch",
    "description": "Lernportal mit verschiedenen Modulen und Materialien."
  },
  {
    "id": "ID25",
    "title": "Historiana",
    "url": "https://historiana.eu/",
    "provider": "European Association of History Educators",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Nationalismus , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  ",
    "sourceType": "Bildquellen , Zeitgenössische Bilder, Textquellen ",
    "language": "Englisch",
    "description": "Historiana offers free historical content, ready to use learning activities, and innovative digital tools made by and for history educators across Europe."
  },
  {
    "id": "ID26",
    "title": "Historische Quellen zur deutschen Geschichte im 19. und 20. Jahrhundert",
    "url": "https://www.terno.de/2020/04/14/historische-quellen-zur-deutschen-geschichte-im-19-und-20-jahrhundert/?utm_source=chatgpt.com",
    "provider": "Christoph Terno",
    "subject": "",
    "contentField": "Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Nationalismus , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Europäische Integration, Kalter Krieg  ",
    "sourceType": "Bildquellen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen ",
    "language": "Deutsch",
    "description": "Wichtige Quellen von der Napoleonischen Zeit über die Revolution 1848, Fälschungen wie die Emser Depesche und die Dolchstoßlegende, deutsche Verfassungen im 19. und 20. Jahrhundert und Dokumente zu den beiden deutschen Staaten gibt es in verschiedenen Internet-Portalen."
  },
  {
    "id": "ID27",
    "title": "Interview-Archiv Zwangsarbeit",
    "url": "https://www.zwangsarbeit-archiv.de/",
    "provider": "Freie Universität Berlin",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg ",
    "sourceType": "Audiovisuelle Quellen , Bildquellen , Textquellen , Digitale Quellen",
    "language": "Englisch; Deutsch",
    "description": "Das Interview-Archiv \"\"Zwangsarbeit 1939-1945\"\" erinnert an über zwanzig Millionen Menschen, die für das nationalsozialistische Deutschland arbeiten mussten. Es enthält knapp 600 Audio und Video-Interviews mit ehemaligen Zwangsarbeiterinnen und Zwangsarbeitern aus 26 Ländern. Dazu gibt es Transkripte, Übersetzungen, Fotos und Kurzbiografien."
  },
  {
    "id": "ID28",
    "title": "LAGIS",
    "url": "https://lagis.hessen.de/de/home",
    "provider": "Hessisches Institut für Landesgeschichte",
    "subject": "",
    "contentField": "Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen ",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert, 18. Jahrhundert",
    "eventCategory": "",
    "sourceType": "Bildquellen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Statistiken und/oder Diagramme, Karten ",
    "language": "Deutsch",
    "description": "Hessische Geschichte entdecken und erforschen"
  },
  {
    "id": "ID29",
    "title": "Landeskunde online Baden-Württemberg",
    "url": "https://www.landeskunde-baden-wuerttemberg.de/",
    "provider": "Landeszentrale für politische Bildung BW",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert, 18. Jahrhundert",
    "eventCategory": "Nationalismus , Industrialisierung, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Statistiken und/oder Diagramme, Karten ",
    "language": "Deutsch",
    "description": "Die neue Plattform „BW-entdecken.de“ bietet Lehrkräften, Schülerinnen und Schülern als auch weiteren Interessierten die Möglichkeit, das Land in all seinen Facetten auf interaktive Weise zu erkunden."
  },
  {
    "id": "ID30",
    "title": "LeMo",
    "url": "https://www.dhm.de/lemo/",
    "provider": "Stiftung Haus der Geschichte der Bundesrepublik Deutschland Stiftung Deutsches Historisches Museum, Bundesarchiv",
    "subject": "",
    "contentField": "",
    "timeCategory": "",
    "eventCategory": "Nationalismus , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Europäische Integration, Kalter Krieg  ",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Statistiken und/oder Diagramme, Karten ",
    "language": "Deutsch",
    "description": "Multimediales Informationssystem des Deutschen Historischen Museums Berlin mit ausgewählten Dokumenten, Bildern Audio- und Videodokumenten zur deutschen Geschichte seit dem späten 19. Jahrhundert"
  },
  {
    "id": "ID31",
    "title": "Medienarchiv 68`",
    "url": "https://www.medienarchiv68.de/#/about",
    "provider": "Axel Springer",
    "subject": "",
    "contentField": "Die Menschenrechte in historischer Perspektive, Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Kalter Krieg  , Europäische Integration",
    "sourceType": "Textquellen ",
    "language": "Deutsch",
    "description": "\"\"Bis heute wird die Berichterstattung der Medien von Axel Springer über „1968“ und die Studentenbewegung kontrovers diskutiert. Nicht selten geschieht dies ohne Kenntnis der Berichte selbst. Mit dem Medienarchiv68 will die Axel Springer SE jedem den unkomplizierten Zugriff auf die Originalquellen ermöglichen, um sich selbst ein Bild zu machen.\nRund 5.900 Beiträge, Kommentare, Leserbriefe, Karikaturen, Reportagen, Glossen und Interviews aus den Jahren 1966 bis 1968 zeigen, wie die Redaktionen von Axel Springer über die 68er-Bewegung berichtet haben.\"\""
  },
  {
    "id": "ID32",
    "title": "Mémorial de la Shoah",
    "url": "https://www.memorialdelashoah.org/",
    "provider": "Mémorial de la Shoah - Gedenkstätten der Shoah in Frankreich",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Holocaust und Erinnerungskultur ",
    "sourceType": "Bildquellen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Karten ",
    "language": "Englisch; Deutsch",
    "description": "Die Gedenkstätte der Shoah hat Ressourcen verschiedener Art für Lehrer und Erzieher zusammengestellt und ausgewählt, die das junge Publikum mit der Geschichte der Shoah vertraut machen oder mit ihren Schülern einen bestimmten Aspekt der Zeit des Zweiten Weltkriegs vertiefen möchten. global und das Unterfangen der Verfolgung und Vernichtung der europäischen Juden."
  },
  {
    "id": "ID33",
    "title": "Offene-Geschichte.de",
    "url": "https://offene-geschichte.de",
    "provider": "Sonderforschungsbereich 923 »Bedrohte Ordnungen« der Universität Tübingen",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Islamische Welt - christliche Welt: Begegnung zweier Kulturen in Mittelalter und früher Neuzeit , Die Menschenrechte in historischer Perspektive, Friedensschlüsse und Ordnung des Friedens in der Moderne , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen ",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Zweiter Weltkrieg , Europäischer Imperialismus, Kalter Krieg  , Nationalismus ",
    "sourceType": "Bildquellen , Zeitgenössische Bilder, Textquellen , Karten ",
    "language": "Deutsch",
    "description": "Test Die Plattform Offene-Geschichte.de zielt auf ein selbstständiges historisches Denken der Lernenden, das sie auf dem Weg zu einer eigensinnigen, selbst verfassten Geschichtserzählung unterstützt. Die Lernplattform für Geschichte steht an ihrem Anfang. Die gegenwärtige pandemische Bedrohung legte einen raschen Start nahe. Es folgen in den kommenden drei Jahren weitere Module und es werden ursprünglich vorgesehene technische Erweiterungen und weitere didaktische Entwicklungen laufend integriert. Der Name »Offene Geschichte« ist auf mehrfache Weise programmatisch zu verstehen:"
  },
  {
    "id": "ID34",
    "title": "Online Edition. Akten der Reichskanzlei",
    "url": "https://aktenreichskanzlei.bundesarchiv.de/",
    "provider": "Das Bundesarchiv ",
    "subject": "",
    "contentField": "Friedensschlüsse und Ordnung des Friedens in der Moderne , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Die moderne Industriegesellschaft zwischen Fortschritt und Krise",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Nationalismus , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS",
    "sourceType": "Textquellen , Zeitgenössische Bilder",
    "language": "Deutsch",
    "description": "\"\"Die digitalisierte Fassung der historisch-kritischen Quellenedition des Fonds „R 43 Reichskanzlei“ – Protokolle der Kabinettssitzungen, Ministerbesprechungen und weitere Dokumente\"\""
  },
  {
    "id": "ID35",
    "title": "Open Memory Box",
    "url": "https://open-memory-box.de/",
    "provider": "Verschiedene",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Die Menschenrechte in historischer Perspektive",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Kalter Krieg  ",
    "sourceType": "Audiovisuelle Quellen ",
    "language": "Deutsch",
    "description": "Sammlung privater DDR-Schmalfilme."
  },
  {
    "id": "ID36",
    "title": "Österreichische Nationbibliothek",
    "url": "https://anno.onb.ac.at/",
    "provider": "Österreichische Nationalbibliothek",
    "subject": "",
    "contentField": "Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Nationalismus ",
    "sourceType": "Textquellen , Bildquellen , Karikaturen ",
    "language": "Deutsch",
    "description": "ANNO (AustriaN Newspaper Online) ist der virtuelle Zeitungslesesaal der Österreichischen Nationalbibliothek. In ANNO kann in historischen österreichischen Zeitungen und Zeitschriften online geblättert, gelesen und gesucht werden. "
  },
  {
    "id": "ID37",
    "title": "OutHistory",
    "url": "https://outhistory.org",
    "provider": "OutHistory",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Weimarer Republik, Deutschland im NS",
    "sourceType": "Bildquellen , Textquellen , Digitale Quellen",
    "language": "Englisch",
    "description": "OutHistory is a public history website that aims to generate, present, and promote high-quality evidence-based LGBTQ historical research for LGBTQ and general audiences. We also work to foster the development and growth of broad and diverse communities of people interested in learning about and producing LGBTQ histories. We are especially interested in under-represented histories and historical research that contributes to positive social change. Most but not all of the current content focuses on the United States and Canada, sometimes in larger transnational contexts."
  },
  {
    "id": "ID38",
    "title": "Quellen zur deutschen Kolonialgeschichte",
    "url": "https://www.bundesarchiv.de/DE/Content/Virtuelle-Ausstellungen/Deutsche-Kolonialgeschichte/deutsche-kolonialgeschichte.html",
    "provider": "Bundesarchiv",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Bildquellen , Textquellen , Zeitgenössische Bilder, Statistiken und/oder Diagramme, Karten ",
    "language": "Deutsch",
    "description": "Sammlung und Galerien zur Deutschen Geschichte."
  },
  {
    "id": "ID39",
    "title": "Sammlung Judaica der Goethe-Universität Frankfurt",
    "url": "https://sammlungen.ub.uni-frankfurt.de/judaica",
    "provider": "Goethe Universität Frankfurt am Main",
    "subject": "",
    "contentField": "Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert ",
    "timeCategory": "19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Nationalismus , Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg ",
    "sourceType": "Textquellen , Bildquellen ",
    "language": "Deutsch",
    "description": "Die Judaica Sammlung in der Frankfurter Universitätsbibliothek stellt die größte Judaica- und Hebraica Sammlung in Deutschland dar und zählt weltweit zu den bedeutendsten Sammlungen ihrer Art."
  },
  {
    "id": "ID40",
    "title": "segu Geschichte",
    "url": "https://segu-geschichte.de/",
    "provider": "SeGu",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Islamische Welt - christliche Welt: Begegnung zweier Kulturen in Mittelalter und früher Neuzeit , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "1789 Französische Revolution , Nationalismus , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Textquellen , Statistiken und/oder Diagramme, Karten ",
    "language": "Deutsch",
    "description": "Projekt segu: selbstgesteuert-entwickelnder Geschichtsunterricht"
  },
  {
    "id": "ID41",
    "title": "Sprechen trotz allem",
    "url": "https://www.sprechentrotzallem.de/deu",
    "provider": "Stiftung Denkmal für die ermordeten Juden Europas",
    "subject": "",
    "contentField": "Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Holocaust und Erinnerungskultur , Deutschland im NS",
    "sourceType": "Audiovisuelle Quellen ",
    "language": "Deutsch",
    "description": "Lebensgeschichtliche Interviews mit Überlebenden der nationalsozialistischen Verfolgung"
  },
  {
    "id": "ID42",
    "title": "SWR Archivradio",
    "url": "https://www.swr.de/swrkultur/wissen/archivradio/",
    "provider": "SWR",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Audiovisuelle Quellen ",
    "language": "Deutsch",
    "description": "Das Archivradio der ARD publiziert historische Tonaufnahmen"
  },
  {
    "id": "ID43",
    "title": "The British Newspaper Archive ",
    "url": "https://www.britishnewspaperarchive.co.uk/",
    "provider": "British Library",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Nationalismus , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  ",
    "sourceType": "Textquellen , Bildquellen ",
    "language": "Englisch",
    "description": "The British Newspaper Archive is a partnership between the British Library and Findmypast to digitise the British Library's vast collection of newspapers."
  },
  {
    "id": "ID44",
    "title": "United States Holocaust Memorial Museum ",
    "url": "https://www.ushmm.org/de",
    "provider": "United States Holocaust Memorial Museum ",
    "subject": "",
    "contentField": "Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Holocaust und Erinnerungskultur , Zweiter Weltkrieg ",
    "sourceType": "Bildquellen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Statistiken und/oder Diagramme, Digitale Quellen",
    "language": "Englisch; Deutsch",
    "description": "A living memorial to the Holocaust, the United States Holocaust Memorial Museum inspires citizens and leaders worldwide to confront antisemitism and hatred, prevent genocide, and promote human dignity. A nonpartisan, federal educational institution chartered by a unanimous Act of Congress in 1980, the Museum’s permanent place on the National Mall is guaranteed by federal support, and its far-reaching educational programs and global impact are made possible by generous donors."
  },
  {
    "id": "ID45",
    "title": "Universität Heidelberg - Zeitungsarchiv",
    "url": "https://www.ub.uni-heidelberg.de/helios/digi/zeitungen_titel.html",
    "provider": "Universität Heidelberg",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "Industrialisierung, Nationalismus , Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS",
    "sourceType": "Bildquellen , Karikaturen , Textquellen ",
    "language": "Deutsch",
    "description": "Digitalsat von Zeitungen "
  },
  {
    "id": "ID46",
    "title": "Universität Tübingen, Fachbereich Geschichtswissenschaft",
    "url": "https://uni-tuebingen.de/fakultaeten/philosophische-fakultaet/fachbereiche/geschichtswissenschaft/studium/beratung-und-hilfe/studierende-helfen-studierenden/nuetzliche-links/online-frei-zugaengliche-quellen/#c106871,%E2%80%AFverschiedene%E2%80%AFQuellenzugänge",
    "provider": "Uni Tübingen",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Islamische Welt - christliche Welt: Begegnung zweier Kulturen in Mittelalter und früher Neuzeit , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert, 20. Jahrhundert",
    "eventCategory": "1789 Französische Revolution , Nationalismus , Industrialisierung, Europäischer Imperialismus, Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  ",
    "sourceType": "Bildquellen , Karikaturen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Statistiken und/oder Diagramme, Karten , Digitale Quellen",
    "language": "Deutsch",
    "description": "Quellensammlung: Zeitübergreifende Quellen"
  },
  {
    "id": "ID47",
    "title": "VD17 Das Verzeichnis der im deutschen Sprachraum erschienenen Drucke des 17 Jahrhunderts",
    "url": "http://www.vd17.de/datenbankinformation/inhalt/",
    "provider": "Herzog August Bibliothek",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive ",
    "timeCategory": "18. Jahrhundert",
    "eventCategory": "1789 Französische Revolution , Nationalismus ",
    "sourceType": "Textquellen ",
    "language": "Deutsch",
    "description": "Enthält Drucke des 17. Jahrhunderts"
  },
  {
    "id": "ID48",
    "title": "Visual History Archive",
    "url": "https://sfi.usc.edu/vha/access",
    "provider": "University of Southern California, Shoah Foundation",
    "subject": "",
    "contentField": "Die Menschenrechte in historischer Perspektive, Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg ",
    "sourceType": "Audiovisuelle Quellen ",
    "language": "Englisch",
    "description": "weltweit größte Oral-History Sammlung zum Nationalsozialismus"
  },
  {
    "id": "ID49",
    "title": "Yad Vashem",
    "url": "https://www.yadvashem.org/de/archive.html",
    "provider": "The Holocaust Martyrs' and Heroes' Remembrance Authority",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Holocaust und Erinnerungskultur , Deutschland im NS",
    "sourceType": "Bildquellen , Zeitgenössische Bilder, Audiovisuelle Quellen , Textquellen , Karten ",
    "language": "Englisch; Deutsch",
    "description": "Staatlich israelische „Gedenkstätte des Holocausts und des Heldenmuts\"\", bedeutendste Gedenkstätte, die an die nationalsozialistische Judenvernichtung erinnert und sie wissenschaftlich dokumentiert"
  },
  {
    "id": "ID50",
    "title": "ZEFYS Amtspresse Preußens",
    "url": "https://zefys.staatsbibliothek-berlin.de/search/Amtspresse%20Preu%C3%9Fens/",
    "provider": "Staatsbibliothek Berlin Preußischer Kulturbesitz",
    "subject": "",
    "contentField": "Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert ",
    "timeCategory": "18. Jahrhundert, 19. Jahrhundert",
    "eventCategory": "Nationalismus , Industrialisierung, Europäischer Imperialismus",
    "sourceType": "Textquellen ",
    "language": "Deutsch",
    "description": "Amtspresse Preußens, zweite Hälfte des 19. Jahrhunderts , aber auch andere Zeitungen"
  },
  {
    "id": "ID51",
    "title": "Zeitzeugen-Archiv der Bundesstiftung Aufarbeitung",
    "url": "https://www.zeitzeugenbuero.de/",
    "provider": "Bundesstiftung zur Aufarbeitung der SED-Diktatur",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Friedensschlüsse und Ordnung des Friedens in der Moderne , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Die Menschenrechte in historischer Perspektive",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Kalter Krieg  , Europäische Integration",
    "sourceType": "Audiovisuelle Quellen , Textquellen , Bildquellen ",
    "language": "Deutsch",
    "description": "Das Zeitzeugenbüro ist ein Angebot der Bundesstiftung zur Aufarbeitung der SED-Diktatur. Die Stiftung fördert die Aufarbeitung der Ursachen, Geschichte und Folgen der Diktatur in der SBZ und DDR, begleitet den Prozess der deutschen Einheit und wirkt international an der Aufarbeitung von kommunistischen Diktaturen mit."
  },
  {
    "id": "ID52",
    "title": "Zeitzeugen-Portal",
    "url": "https://www.zeitzeugen-portal.de/",
    "provider": "Stiftung der Geschichte der BRD",
    "subject": "",
    "contentField": "Erfahrungen mit Fremdsein in weltgeschichtlicher Perspektive , Die Menschenrechte in historischer Perspektive, Die moderne Industriegesellschaft zwischen Fortschritt und Krise, Die Zeit des Nationalsozialismus - Voraussetzung, Herrschaftsstrukturen, Nachwirkungen und Deutungen , Nationalismus, Nationalstaat und deutsche Identität im 19. und 20. Jahrhundert , Friedensschlüsse und Ordnung des Friedens in der Moderne ",
    "timeCategory": "20. Jahrhundert",
    "eventCategory": "Erster Weltkrieg, Weimarer Republik, Deutschland im NS, Holocaust und Erinnerungskultur , Zweiter Weltkrieg , Kalter Krieg  , Europäische Integration",
    "sourceType": "Audiovisuelle Quellen ",
    "language": "Deutsch",
    "description": "Der Bestand an Zeitzeugeninterviews umfasst das 20. und 21. Jahrhundert. Ob Tradition und Kontinuität oder Wandel und Umbruch: Die Erzählungen der Zeitzeugen zeichnen vielfältige subjektive, persönliche Bilder der deutschen Geschichte." }
  ];
    
